version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432

  flyway:
    image: flyway/flyway
    command: ["-url=jdbc:postgresql://db:5432/${POSTGRES_DB}", "-user=${POSTGRES_USER}", "-password=${POSTGRES_PASSWORD}", "migrate"]
    volumes:
      - ./sql:/flyway/sql
    depends_on:
      - db
    restart: on-failure


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      flyway:
        condition: service_completed_successfully	


