# La configuraci贸n de este archivo solamente es relevante cuando la ejecuci贸n es local;
# no sirve si la ejecuci贸n es en la nube.

services:

  db:
    image: postgres
    restart: always
    environment:

      # Respecto a las siguientes tres variables, Docker Compose busca
      # sus valores en un archivo '.env', s贸lo cuando se utiliza el comando
      # 'docker compose up'. Por eso es que no hace falta definir el prefijo '.env'.
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

      # Especifica la zona horaria de Argentina.
      TZ: "-03"

    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080



