# https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/

apiVersion: v1
kind: Service
metadata:
  name: bd-service

# https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/#ServiceSpec
spec:
  selector:
    name: bd-pod
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432