# https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/

apiVersion: v1
kind: Service
metadata:
  name: back-service

# https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/#ServiceSpec
spec:
  selector:
    name: back-pod
  ports:
  - protocol: TCP
    port: 6060
    targetPort: 6060