# https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/

apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  namespace: default

# https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/#DeploymentSpec
spec:
  replicas: 1

  # https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors
  # https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/label-selector/#LabelSelector
  selector:
    matchLabels:
      name: front-pod

  # https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-template-v1/#PodTemplate
  template:

    # https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/object-meta/#ObjectMeta
    metadata:

      # https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
      labels: # Todas las etiquetas son privadas, por la falta de prefijo.
        name: front-pod
        tier: frontend

    # https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#PodSpec
    spec:

      # https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#Container
      containers:
      - name: front-container
        image: # facundol/FRONT EN DOCKER HUB
        env:
        - name: "PORT"
          value: "4040"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: front-secrets
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: front-secrets
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: front-secrets
        - name: CLIENT_ORIGIN_URL
          valueFrom:
            secretKeyRef:
              name: front-secrets
        - name: AUTH0_DOMAIN
          valueFrom:
            secretKeyRef:
              name: front-secrets
        - name: AUTH0_AUDIENCE
          valueFrom:
            secretKeyRef:
              name: front-secrets
        - name: AUTH0_APP_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: front-secrets
        - name: AUTH0_APP_SECRET
          valueFrom:
            secretKeyRef:
              name: front-secrets
        - name: AUTH0_DB_CONNECTION
          valueFrom:
            secretKeyRef:
              name: front-secrets
        - name: AUTH0_ROLID_DOCENTE
          valueFrom:
            secretKeyRef:
              name: front-secrets

      # https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
      # https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#scheduling
      #
      # El siguiente código indica que el pod puede ser desplegado en nodos de tipo spot.
      tolerations:
      - key: instance_type
        operator: Equal
        value: spot
        effect: NoSchedule