
application:
  audience: ${env.AUTH0_AUDIENCE}
  client-origin-url: ${env.CLIENT_ORIGIN_URL}

logging:
  level:
    root: INFO

server:
  error:
    whitelabel:
      enabled: false
  port: ${env.PORT}

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${env.AUTH0_DOMAIN}/
  datasource:
    url: ${env.POSTGRES_URL}
    username: ${env.POSTGRES_USER}
    password: ${env.POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # Reemplaza con el dialecto correspondiente a tu base de datos

  flyway:
    enabled: true
    url: ${env.POSTGRES_URL}
    user: ${env.POSTGRES_USER}
    password: ${env.POSTGRES_PASSWORD}
    locations:
    - classpath:db/migration
    - filesystem:flyway-dev

  web:
    resources:
      add-mappings: false
