name: back-actions
run-name: back-actions (@${{ github.triggering_actor }})

on:
  push:
    branches:
      - cloud

jobs:
  up: # [UP]
    name: Base up
    if: startsWith(github.event.head_commit.message, '[UP]')
    runs-on: ubuntu-latest
    environment: back
    steps:

    # Checkout de la rama. 
    - name: Checkout code
      uses: actions/checkout@v3

      # Crea los archivos necesarios para los siguientes pasos.
    - name: file creation
      working-directory: src/k8s
      run: |

        # Guarda el token en un archivo para que lo utilice Terraform.
        echo -n '${{ secrets.BACK_SECRETS }}' > 00-back-secrets.yaml

        # Crea los secretos para el certificado TLS.
        echo -n '${{ secrets.BD_SECRETS }}' > 00-bd-secrets.yaml

   # Configura Google Cloud.
    - name: Google Cloud authentication
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
    - name: Google Cloud SDK setup
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: '>= 363.0.0'
        install_components: 'kubectl'
    - name: GCloud config
      run: |

        gcloud info

        gcloud components list

        gcloud container clusters get-credentials primary --region=us-central1-a
  
    # Despliega los objectos en la nube.
    - name: Kubernetes deploy
      working-directory: src/k8s
      run: |

        set -e

        # Aplica los cambios de Kubernetes.
        echo "Aplicando los cambios de Kubernetes..."
        kubectl apply \
          -f 00-back-secrets.yaml \
          -f 00-bd-secrets.yaml \
          -f 01-service-bd.yaml \
          -f 02-service-back.yaml \
          -f 03-deploy-bd.yaml \
          -f 04-deploy-back.yaml
        echo "Cambios aplicados."